#vaadin.launch-browser=true
#spring.application.name=DbHelpMe

spring:
    application:
        name: DbHelpMe

    datasource:
        username: root
        password: _mySql.io0
        url: jdbc:mysql://localhost:3306/mydatabase

    jpa:
        hibernate:
            ddl-auto: update
#        show-sql: true

        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
