#vaadin.launch-browser=true
#spring.application.name=DbHelpMe

spring:
    application:
        name: DbHelpMe

    datasource:
        username: root
        password: 130405
        url: jdbc:mysql://localhost:3306/mydatabase

    jpa:
        hibernate:
            ddl-auto: none

        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect

    server:
        port: 8080